// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RequestPb.proto

package com_hirpc_entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestInner struct {
	HirpcVersion         *string           `protobuf:"bytes,1,req,name=hirpcVersion" json:"hirpcVersion,omitempty"`
	ServicePath          *string           `protobuf:"bytes,2,req,name=servicePath" json:"servicePath,omitempty"`
	ServiceName          *string           `protobuf:"bytes,3,req,name=serviceName" json:"serviceName,omitempty"`
	ServiceVersion       *string           `protobuf:"bytes,4,opt,name=serviceVersion" json:"serviceVersion,omitempty"`
	Header               map[string]string `protobuf:"bytes,5,rep,name=header" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParameterType        []string          `protobuf:"bytes,6,rep,name=parameterType" json:"parameterType,omitempty"`
	Data                 *string           `protobuf:"bytes,7,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RequestInner) Reset()         { *m = RequestInner{} }
func (m *RequestInner) String() string { return proto.CompactTextString(m) }
func (*RequestInner) ProtoMessage()    {}
func (*RequestInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_57cba95e4c84b041, []int{0}
}

func (m *RequestInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInner.Unmarshal(m, b)
}
func (m *RequestInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInner.Marshal(b, m, deterministic)
}
func (m *RequestInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInner.Merge(m, src)
}
func (m *RequestInner) XXX_Size() int {
	return xxx_messageInfo_RequestInner.Size(m)
}
func (m *RequestInner) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInner.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInner proto.InternalMessageInfo

func (m *RequestInner) GetHirpcVersion() string {
	if m != nil && m.HirpcVersion != nil {
		return *m.HirpcVersion
	}
	return ""
}

func (m *RequestInner) GetServicePath() string {
	if m != nil && m.ServicePath != nil {
		return *m.ServicePath
	}
	return ""
}

func (m *RequestInner) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *RequestInner) GetServiceVersion() string {
	if m != nil && m.ServiceVersion != nil {
		return *m.ServiceVersion
	}
	return ""
}

func (m *RequestInner) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RequestInner) GetParameterType() []string {
	if m != nil {
		return m.ParameterType
	}
	return nil
}

func (m *RequestInner) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestInner)(nil), "com.hirpc.entity.RequestInner")
	proto.RegisterMapType((map[string]string)(nil), "com.hirpc.entity.RequestInner.HeaderEntry")
}

func init() { proto.RegisterFile("RequestPb.proto", fileDescriptor_57cba95e4c84b041) }

var fileDescriptor_57cba95e4c84b041 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xbb, 0x4d, 0xfa, 0x3a, 0x75, 0x3c, 0x3c, 0x04, 0xbd, 0x94, 0x21, 0x12, 0x3c,
	0xe4, 0xe0, 0x49, 0x3d, 0x16, 0x04, 0xbd, 0xc8, 0x08, 0xe2, 0x3d, 0xeb, 0x9e, 0xb4, 0xb8, 0x26,
	0x35, 0x4d, 0x07, 0xfd, 0xa4, 0x7e, 0x1d, 0x59, 0x56, 0xb5, 0xdd, 0xed, 0xff, 0x7e, 0xfc, 0x92,
	0xfc, 0x93, 0xc0, 0xb9, 0xa4, 0xaf, 0x96, 0x1a, 0xb7, 0x5a, 0x8b, 0xda, 0x1a, 0x67, 0x70, 0x91,
	0x9b, 0x4a, 0x14, 0xa5, 0xad, 0x73, 0x41, 0xda, 0x95, 0xae, 0x5b, 0x7e, 0x87, 0x30, 0xef, 0xad,
	0x17, 0xad, 0xc9, 0xe2, 0x12, 0xe6, 0x5e, 0x78, 0x27, 0xdb, 0x94, 0x46, 0xb3, 0x20, 0x0d, 0x79,
	0x2c, 0x47, 0x0c, 0x53, 0x48, 0x1a, 0xb2, 0xbb, 0x32, 0xa7, 0x95, 0x72, 0x05, 0x0b, 0xbd, 0x32,
	0x44, 0x03, 0xe3, 0x55, 0x55, 0xc4, 0xa2, 0x91, 0xb1, 0x47, 0x78, 0x03, 0x67, 0xfd, 0xf8, 0x7b,
	0xd2, 0x24, 0x0d, 0x78, 0x2c, 0x8f, 0x28, 0x66, 0x30, 0x2b, 0x48, 0x6d, 0xc8, 0xb2, 0x69, 0x1a,
	0xf1, 0xe4, 0xee, 0x56, 0x1c, 0xdf, 0x41, 0x0c, 0xfb, 0x8b, 0x67, 0x2f, 0x3f, 0x69, 0x67, 0x3b,
	0xd9, 0xaf, 0xc4, 0x6b, 0x38, 0xad, 0x95, 0x55, 0x15, 0x39, 0xb2, 0x6f, 0x5d, 0x4d, 0x6c, 0x96,
	0x46, 0x3c, 0x96, 0x63, 0x88, 0x08, 0x93, 0x8d, 0x72, 0x8a, 0x9d, 0xf8, 0x1e, 0x3e, 0x5f, 0x3e,
	0x40, 0x32, 0xd8, 0x10, 0x17, 0x10, 0x7d, 0x52, 0xc7, 0x02, 0x6f, 0xec, 0x23, 0x5e, 0xc0, 0x74,
	0xa7, 0xb6, 0x2d, 0xb1, 0xd0, 0xb3, 0xc3, 0xf0, 0x18, 0xde, 0x07, 0x19, 0x87, 0xab, 0xff, 0xa6,
	0xfe, 0xf9, 0x73, 0xb3, 0x3d, 0x84, 0x75, 0xfb, 0x91, 0xc5, 0x7f, 0x7f, 0xf3, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x2a, 0x4f, 0x03, 0x15, 0xa7, 0x01, 0x00, 0x00,
}
