// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ResponsePb.proto

package com_hirpc_entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseInner struct {
	Error                *string  `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	ReturnType           []string `protobuf:"bytes,2,rep,name=returnType" json:"returnType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseInner) Reset()         { *m = ResponseInner{} }
func (m *ResponseInner) String() string { return proto.CompactTextString(m) }
func (*ResponseInner) ProtoMessage()    {}
func (*ResponseInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_c865d6e1ec83d095, []int{0}
}

func (m *ResponseInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInner.Unmarshal(m, b)
}
func (m *ResponseInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInner.Marshal(b, m, deterministic)
}
func (m *ResponseInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInner.Merge(m, src)
}
func (m *ResponseInner) XXX_Size() int {
	return xxx_messageInfo_ResponseInner.Size(m)
}
func (m *ResponseInner) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInner.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInner proto.InternalMessageInfo

func (m *ResponseInner) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *ResponseInner) GetReturnType() []string {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func init() {
	proto.RegisterType((*ResponseInner)(nil), "com.hirpc.entity.ResponseInner")
}

func init() { proto.RegisterFile("ResponsePb.proto", fileDescriptor_c865d6e1ec83d095) }

var fileDescriptor_c865d6e1ec83d095 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x0d, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x48, 0xce,
	0xcf, 0xd5, 0xcb, 0xc8, 0x2c, 0x2a, 0x48, 0xd6, 0x4b, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x54, 0x72,
	0xe5, 0xe2, 0x85, 0xa9, 0xf2, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x12, 0xe1, 0x62, 0x4d, 0x2d, 0x2a,
	0xca, 0x2f, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xe4, 0xb8, 0xb8, 0x8a,
	0x52, 0x4b, 0x4a, 0x8b, 0xf2, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14, 0x98, 0x35, 0x38, 0x83,
	0x90, 0x44, 0x9c, 0x34, 0xb9, 0xa4, 0x11, 0x46, 0x83, 0xed, 0x4a, 0xce, 0xcf, 0x81, 0x30, 0x92,
	0x4a, 0xd3, 0x9c, 0xb8, 0x10, 0x2e, 0x01, 0x04, 0x00, 0x00, 0xff, 0xff, 0x67, 0x9f, 0x29, 0x80,
	0x96, 0x00, 0x00, 0x00,
}
